### ISSUE TITLE
Unable to load bioc2016singlecell package

### ISSUE THREAD

**Issue by biovitus** [drisso/bioc2016singlecell#1]
Dear Sir,

I am trying to install bioc2016singlecell package in R version 3.2.4 Revised (64 bit) on Windows 10 platform. It installs and but does not shows up in list of packages through the GUI. It is present in the library folder of R and when I try to load the package it gives the following error.
> library(bic2016singlecell-master)
Error in library(bic2016singlecell - master) : 
  'package' must be of length 1

I like to know if you can help in fixing this error.

Appreciate your help.

Sincerely,

Biovitus

**Comment by drisso** [comment]
The name of the package is `bioc2016singlecell` (without the `-master`).

It could be as easy as just typing 

```{r}
library(bioc2016singlecell)
```

If that doesn't work, can you please tell me the command that you use to install it?
